### ISSUE TITLE
Everything on the Today display resets after Midnight to their opening times even if event is still open

### ISSUE THREAD

**Issue by kd2gfn** [superlou/zenkaikon24#18] opened 2024-03-07 16:21 UTC
I set the time to 23:30 on the 22nd, when time passed midnight everything was updated but I saw a problem on the TODAY display.

Everything on the Today display reset to their opening times even if it was still open.

Example: The shuttle bus stops at 1:30 am, but when time passed midnight and a guidebook update occurred, the shuttle bus changed from closing at 1:30 am to opening at 9:30 am.
                 This happened for other events that stay open past midnight as well.

**Comment by superlou** [comment] 2024-03-07 17:01
What was the specific debug datetime and acceleration you were using?

Edit: Just saw your email. Added it to your description.

**Comment by superlou** [comment] 2024-03-07 17:47
The logic for an all-day session is simply (where min_duration is 3.5 hours):

        if s["starts_today"] and s["duration"] > min_duration

The logic for `starts_today` is:

```py
def starts_today(now, start):
    today_midnight = now.replace(hour=0, minute=0, second=0, microsecond=0)
    today_start = today_midnight + timedelta(hours=5)
    today_finish = today_start + timedelta(hours=24)
    return today_start <= start < today_finish
```

I think the problem is that the threshold for something starting "today" can't be midnight. It has to be something like 4 am.

**Comment by kd2gfn** [comment] 2024-03-07 19:46
I did 2 ways to check.

First way was with an acceleration of 2. I set date and starting time to
2024-03-22T23:30:00 and let it run. When it went past midnight and did a
guidebook update the today screen reset everything to there starting times
for the day even when when some events had an ending of 1:30 am.

Second was with an acceleration of zero and date/time2024-03-22T00:01:00.
It did a guidebook update and same thing happened. Today screen events were
set to opening and none of the events that should close after midnight
showed the closing time

Bert

**Comment by superlou** [comment] 2024-03-07 21:31
Do you know what time the last event in a "day" ends?

**Comment by kd2gfn** [comment] 2024-03-07 22:02
You would check with Chet as I'm at work now, don't have access to
guidebook here. I know there are events that go to 1:30 am, but not sure if
anything goes beyond that

**Comment by superlou** [comment] 2024-03-08 00:19
Figured it out. The problem is that the calculation of midnight is no good when the day rolls over. Going to try to push an update tonight.

**Comment by superlou** [comment] 2024-03-08 01:32
Package is updated. It should be treating a "day" as 4 am one day to 4 am the next.

**Comment by kd2gfn** [comment] 2024-03-08 01:57
I will update and give a try tonight.

**Comment by kd2gfn** [comment] 2024-03-08 18:44
updated the pi, let it run at acceleration of 3. all looks good so far,

**Comment by superlou** [comment] 2024-03-15 01:22
Closing as complete. Let me know if there are issues with this still!

**Closed as completed by superlou** 2024-03-15 01:22 UTC
Labels: bug
